name: Create Tag

on:
  pull_request:
    types:
      - closed
    branches: [develop]
jobs:
  Create_Tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Klemensas/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"